const paragraphs = {
  1: "This site is about documenting code, in various forms. The documentation will serve multiple purposes. These purposes include, but aren’t limited to: (a) providing workable examples in code that others can use for whatever they see fit, (b) exploring code concepts, (c) exploring learning-to-code concepts, (d) exploring documentation concepts, and (e) engaging in creative expression through the act of writing about these topics.",
  2: "There are two types of code you will find documentation for on this site: (a) code that I’ve written myself, and (b) code that someone else has written. Sometimes I will write my own code instead of making use of someone else’s code because I enjoy the activity, or want to experiment with a library or technology. On other occasions, I will write my own code because it’s convenient, and allows more opportunity for flexibility when exploring a particular code or documentation concept.",
  3: "That said, I want to emphasize that my code may not always embody best practices. Sometimes this is because of time constraints, where I have to do things quick and dirty if I want to have time to focus on a particular issue. However, it can also be because the best way to do things is difficult for me or I haven’t yet learned how to do it.",
  4: "There are a few ways I aim to foster transparency in documentation on this site. In addition to providing you with code examples and snippets, I will provide commentary in various forms, supplemented with annotations and references. Sometimes I get things wrong, and if you think I do, you’re welcome to email me (see the Contact tab) and let me know why I’m mistaken in my claims.",
  5: "You will find references in two places on this site: (a) a complete list on the references sub-section in the Resources section of the main menu, and (b) references relevant to the topic in the content sections.",
  6: "Sometimes people look to references as a source of authority. In these situations, they don’t want to investigate the content on its own merits, or simply don’t have the time or ability to do so. As such, they take certain references as a proxy of sorts. “If that smart girl who has studied the topic for a long time says so, well, I guess that’s good enough for me.” I’m not a big fan of this sort of approach to references, but at best we only have enough time to learn a few things well, and necessity dictates that we rely, to a greater or lesser degree, on experts for everything else.",
  7: "That said, the references I supply here aren’t meant to act as a source of authority, but simply additional content that may or may not contribute something useful to your understanding. For each reference in the associated content section, I’ll provide a short description of why it could be useful.",
};

export { paragraphs };
