const paragraphs = {
  1: "Once upon a time, on an Earth that never was, the citizens of that fair planet were facing an unprecedented crisis. A star-faring race of reptilian predators had come to swallow the Milky Way, and they did not care for peace or compromise. The inhabitants of Earth feared for the future, and they grew desperate after it became clear that only one end awaited them, should they lose this war. The reptiles had sent videos of their monstrous feeding vats. They were indifferent to cries for mercy, and amused by the threats, prayers, and attempts at bargaining. Their answer was always the same: human in, goo out.",
  2: "Naturally, the humans could not let this stand. So, they set in motion a plan. An organization was born, a juggernaut of such proportions that it dwarfed anything seen in the short history of homo sapiens. This organization had many parts and many purposes. But it was clear that it lurched toward a singular goal. The machinery of war would be realized in weapons of hitherto unimaginable destructive power, and the components that made up those weapons would be built by specialized teams of Earth’s finest engineers.",
  3: "The council that oversaw this organization had placed their hopes, and a substantial portion of Earth’s resources, on a very special weapon. This weapon was named—perhaps unwisely—the Godzilla Beam. It was a long-range ground-to-orbit gravity fluctuator. The physicists dreamt it up, the mathematicians validated the empirical models, and it was now up to the engineers to carry the torch forward. An artifact of such daunting complexity had never before been concretely conceived of, let alone built. The engineers were skeptical, most did not think the project could succeed. But if the alternative was a goo vat, all they could do was shrug, roll up their sleeves, and let the dice roll.",
  4: "One of the critical parts of the Godzilla Beam was the targeting system. Because of its importance, leadership had placed this component in the hands of a man known only as Professor Jack. He had pioneered www protocols before there was a world wide web and laid the groundwork for decision tree and neural network technologies that later gave rise to models biologists used to breed mutant household pets of startling intelligence. Although he was known for his uncompromising character and eccentricity, he had never once failed to deliver when called upon. As far as the top brass were concerned, he was the right man for the job.",
  5: "In a Starbucks requisitioned for the war effort, Jack’s team huddled around a gleaming copper table with a high res monitor lighting up an otherwise dark room. Pumpkin-spice lattes in hand, they watched starstruck as Jack hammered away at his CLI. The team had learned early on not to suggest he--or they-- use GUIs. The mere mention of a GUI would set Jack off. He would turn his beetle-eyed gaze upward, proclaiming that GUIs were the tools of feeble minds, and they had ruined an entire generation of programmers.",
  6: 'Eventually, the sounds of mechanical clicking stilled, and Jack rose up from his hawk-like stoop. With a satisfied smile on his craggy face, he said, "It is well done. We are nearing the end."',
  7: 'At Jack’s words, most of the team felt relief, but Mary frowned. Gathering her courage, she said slowly, "Sir, I think we’ve forgotten something. What about the documentation for our targeting system?"',
  8: 'Jack looked puzzled, "Mary, what do you mean?"',
  9: '"Our targeting system is incredibly complex, and it has to integrate with the Godzilla Beam’s other systems. If we don’t provide documentation on how our system works, no one will be able to use it."',
  10: 'Jack waved his hand in dismissal, "The documentation will be complete when the code is complete. The code is self-documenting."',
  11: 'Mary replied, "It may be self-documenting, but it isn’t a document that just anyone can understand."',
  12: 'Jack gave a throaty laugh, as if he had heard the funniest of jokes, "That cannot be true. Just the other day, I let dearest Floofy read over our latest work. He had no trouble understanding it."',
  13: 'The room was filled with a collective confusion. A moment later, Mary clarified, "Sir, you’re saying that your genetically-modified cat, Floofy, can understand our APIs, data-flows, and interfaces?"',
  14: 'Jack nodded emphatically, "Exactly. If he can do it, anyone can."',
  15: 'It was unclear if Mary shared the undercurrent of disbelief permeating the room, but she said, "That’s very impressive, sir. However, not everyone is quite as talented as Floofy. Perhaps we could request a team of technical writers to document the code in English?  I think that’s something the higher ups would appreciate."',
  16: 'Jack stroked his narrow chin, deep in thought. Finally, he said, "Okay, we can provide them with your English document. But I fail to see the need for these so-called "technical" writers. That’s a sham, if I’ve ever heard one."',
  17: 'Mary objected, "But we just don’t have time to write the documentation ourselves. We need to finish the system!"',
  18: 'Jack smiled, throwing his arms wide in an air of finality, "Of course we will not spend our precious time on so trivial a task. Floofy can write in English. He can understand the code. So, he will write the English document for us."',
  19: "And so it came to pass that the fate of Earth would rest in the questionable paws of a lonesome cat elevated above his nature by human ingenuity and arcane algorithms writ in silicon. But that is a story for another day.",
};

export { paragraphs };
